name: Eleventy Build
on:
  pull_request:
    types:
      - closed
  push:
    branches: 'master'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site 
          publish_branch: gh-pages